name: oncall-handoff
description: 'Generate structured on-call handoff documentation'
version: '1.0.0'
agent: heimdall

inputs:
  outgoing_engineer:
    type: string
    description: 'Engineer ending shift'
    required: true
  incoming_engineer:
    type: string
    description: 'Engineer starting shift'
    required: true

outputs:
  handoff_document:
    path: '{sre_artifacts}/oncall/handoff-{date}.md'

knowledge:
  - incident-response-playbooks
  - runbook-templates

steps:
  - name: step-01-gather-data
    file: steps/step-01-gather-data.md
    description: 'Gather current status and incidents'
  - name: step-02-future-context
    file: steps/step-02-future-context.md
    description: 'Identify upcoming changes and watch items'
  - name: step-03-generate-handoff
    file: steps/step-03-generate-handoff.md
    description: 'Generate and validate handoff document'
