name: cost-analysis
description: 'Analyze infrastructure costs and optimization opportunities'
version: '1.0.0'
agent: heimdall

inputs:
  scope:
    type: string
    description: 'Analysis scope (service, team, all)'
    required: true
  cost_data:
    type: object
    description: 'Cost data from cloud provider'
    required: false

outputs:
  cost_report:
    path: '{sre_artifacts}/cost/analysis-{date}.md'
  recommendations:
    type: array
    description: 'Cost optimization recommendations with ROI'

steps:
  - name: step-01-gather-spend
    file: steps/step-01-gather-spend.md
    description: 'Collect cost data and define scope'
  - name: step-02-analyze-waste
    file: steps/step-02-analyze-waste.md
    description: 'Identify idle resources and over-provisioning'
  - name: step-03-recommendations
    file: steps/step-03-recommendations.md
    description: 'Generate cost optimization report with ROI'
